# fly.toml app configuration file generated for dailyscrum-core on 2024-05-19T08:10:20+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dailyscrum-core'
primary_region = 'sjc'

[build]
  dockerfile = './apps/core/Dockerfile'

[http_service]
  internal_port = 4001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
